repo: "responsive-icon-cards"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - "ul"
      - "ul li"
      - "ul div"
      - "ul img"
      - "ul h2"
      - "ul p"
    search:
      - 'placeholder-circle\.svg'
      - 'Atlas moth'
      - 'Hercules Moth'
      - 'Hercules Moth'

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['html', 'text-size-adjust', '100%']
      - ['html', '-moz-text-size-adjust', '100%']
      - ['html', '-ms-text-size-adjust', '100%']
      - ['html', '-webkit-text-size-adjust', '100%']
      - ['*', 'box-sizing', 'inherit']
      - ['.cards', 'list-style-type', 'none']
      - ['.card']
      - ['.card-img img']
      - ['.card-body h2']
      - ['.card-body p']
      - ['@25em', '.card-img']
      - ['@38em', 'html', 'font-size', '110%']
      - ['@38em', 'html', 'line-height', '1.4']
      - ['@60em', 'html', 'font-size', '120%']
      - ['@60em', 'html', 'line-height', '1.5']
      - ['@90em', 'html', 'font-size', '130%']
    search:
      - '@-moz-viewport'
      - '@-ms-viewport'
      - '@-o-viewport'
      - '@-webkit-viewport'
      - '@viewport'
      - '100%'
      - '1\.3'
      - 'display: inline-block'
      - 'display: block'
    search_not:
      - ['@media.+\(.*max-width', 'Media queries with `max-width` should not be used — use `min-width` instead']
      - ['@media.+\(.*px', 'Pixel units should not be used in media queries — use `em` instead']
      - ['font-size\s*:\s*.+px', 'Pixel units should not be used for `font-size` — use `rem` instead']
      - ['line-height\s*:\s*.+(px|rem|em)', 'Line heights should not have units']
      - ['float:', 'Use `display: inline-block` instead of float to complete this assignment']

screenshots:
  - path: "index.html"
    sizes: [320, 400, 650, 980, 1400]
